<a href="https://colab.research.google.com/github/yoshitha1209/Machine-Learning/blob/main/23003lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A1,A2,A3

In [56]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_excel("/Lab Session Data.xlsx", usecols=['Customer','Candies (#)','Mangoes (Kg)','Milk Packets (#)','Payment (Rs)'])
print("Contents in csv file:\n", df)
A=np.array([df['Candies (#)'],df['Mangoes (Kg)'],df['Milk Packets (#)']]).transpose()
print(A)
C=np.array([df['Payment (Rs)']]).transpose()
print(C)
print("Dimensionality",A.shape[1])
print("Number of vectors",A.shape[0])
print("Rank",np.linalg.matrix_rank(A))
print("Cost",np.matmul(np.linalg.pinv(A),C))
def classifier(C):
  payment=df.groupby('Customer')['Payment (Rs)'].sum()
  classify=payment.apply(lambda x:'Rich' if x>200 else 'Poor')
  return classify
classifier(C)

Contents in csv file:
   Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
Dimensionality 

Customer
C_1     Rich
C_10    Poor
C_2     Rich
C_3     Rich
C_4     Poor
C_5     Rich
C_6     Poor
C_7     Rich
C_8     Rich
C_9     Poor
Name: Payment (Rs), dtype: object

A4





In [73]:
import statistics
df = pd.read_excel("/Lab Session Data.xlsx", sheet_name='IRCTC Stock Price',usecols=['Date','Month','Day','Price','Open','High','Low','Volume','Chg%'])
print("Contents in csv file:\n", df)
print("Mean",statistics.mean(df['Price']))
print("Varience",statistics.variance(df['Price']))
def wednesday(df):
  wed=df[df['Day']=='Wed']
  wed_mean=statistics.mean(wed['Price'])
  pop_mean=statistics.mean(df['Price'])
  return wed_mean,pop_mean,abs(wed_mean-pop_mean)
print(wednesday(df))
def april(df):
  april=df[df['Month']=='Apr']
  april_mean=statistics.mean(april['Price'])
  ap_pop_mean=statistics.mean(df['Price'])
  return april_mean,ap_pop_mean,abs(april_mean-ap_pop_mean)
print(april(df))

Contents in csv file:
              Date Month  Day    Price     Open     High      Low   Volume  \
0    Jun 29, 2021   Jun  Tue  2081.85  2092.00  2126.90  2065.05    1.67M   
1    Jun 28, 2021   Jun  Mon  2077.75  2084.00  2112.45  2068.40  707.73K   
2    Jun 25, 2021   Jun  Fri  2068.85  2084.35  2088.50  2053.10  475.82K   
3    Jun 24, 2021   Jun  Thu  2072.95  2098.00  2098.00  2066.00  541.51K   
4    Jun 23, 2021   Jun  Wed  2078.25  2102.00  2111.40  2072.00  809.62K   
..            ...   ...  ...      ...      ...      ...      ...      ...   
244  Jul 07, 2020   Jul  Tue  1397.40  1410.00  1411.00  1390.05  480.21K   
245  Jul 06, 2020   Jul  Mon  1400.75  1405.50  1415.50  1394.00  614.93K   
246  Jul 03, 2020   Jul  Fri  1405.10  1415.00  1425.00  1398.00  599.49K   
247  Jul 02, 2020   Jul  Thu  1412.35  1440.00  1467.80  1395.30    2.16M   
248  Jul 01, 2020   Jul  Wed  1363.05  1363.65  1377.00  1356.00  383.00K   

       Chg%  
0    0.0020  
1    0.0043  
2   -0.002