<a href="https://colab.research.google.com/github/yoshitha1209/Machine-Learning/blob/main/mllab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAME: CHUNDURI YOSHITHA
REGNO: BL.EN.U4AIE23003
LAB-1

1.


In [3]:
l1=[2,7,4,1,3,6]
def pairs_counting(l1):
  count=0
  for i in range(len(l1)):
    for j in range(i+1,len(l1)):

      if l1[i]+l1[j]==10:
        print(l1[i],l1[j])
        count=count+1
  print("Count:",count)

pairs_counting(l1)



7 3
4 6
Count: 2


2.


In [9]:

def range_list():
  l1 = list(map(int,input("Enter the list: ").split()))
  if len(l1)>3:
    range=max(l1)-min(l1)
    print("Range is ",range)
  else:
    print("Range determination not possible")

range_list()

Enter the list: 7 9 6
Range determination not possible


3.


In [ ]:
import numpy as np
n=int(input("Enter the dimension of matrix:"))
mat=np.random.rand(n,n)
print(mat)
m=int(input("Enter the positive integer:"))
print(pow(mat,m))



Enter the dimension of matrix:3
[[0.20326114 0.36636629 0.36810144]
 [0.14473421 0.3573108  0.98448733]
 [0.09800016 0.4009035  0.12771502]]
Enter the positive integer:2
[[0.04131509 0.13422426 0.13549867]
 [0.02094799 0.127671   0.9692153 ]
 [0.00960403 0.16072362 0.01631113]]


4.


In [10]:
s=input("Enter a string:")
def high_occ(s):
    max_char=max(s,key=s.count)
    max_count=s.count(max_char)
    print(max_char,max_count)
high_occ(s)


Enter a string:hippopotamus
p 3
